### ISSUE TITLE
Collect failed attempts at running (Py)Spark on SAVIO

### ISSUE THREAD

**Issue by davclark** [berkeley-dsc/dlab-finance#1]
I assigned this to @rsoni1, but @justin-mccrary-58 has had some failures as well. I'll also see about creating some failures of my own. 

This also led me to realize that @justin-mccrary-58 was not part of the dlab-finance team, so I just added him – please accept the invitation!

**Comment by rsoni1** [comment]
Here is the trace

[rsoni@ln001 ~]$ srun -p savio -A ac_dlab --qos=nc_debug -N 4 -t 10:0 --pty bash 
[rsoni@n0085 ~]$ 
[rsoni@n0085 ~]$ 
[rsoni@n0085 ~]$ 
[rsoni@n0085 ~]$ source /global/home/groups/allhands/bin/spark_helper.sh
[rsoni@n0085 ~]$ spark-start
starting org.apache.spark.deploy.master.Master, logging to /global/scratch/rsoni/spark/bash.222857/log/spark-rsoni-org.apache.spark.deploy.master.Master-1-n0085.savio0.out
n0088.savio0: Warning: Permanently added 'n0088.savio0,10.0.1.88' (RSA) to the list of known hosts.
n0086.savio0: Warning: Permanently added 'n0086.savio0,10.0.1.86' (RSA) to the list of known hosts.
n0085.savio0: Warning: Permanently added 'n0085.savio0,10.0.1.85' (RSA) to the list of known hosts.
n0087.savio0: Warning: Permanently added 'n0087.savio0,10.0.1.87' (RSA) to the list of known hosts.
n0085.savio0: starting org.apache.spark.deploy.worker.Worker, logging to /global/scratch/rsoni/spark/bash.222857/log/spark-rsoni-org.apache.spark.deploy.worker.Worker-1-n0085.savio0.out
n0086.savio0: starting org.apache.spark.deploy.worker.Worker, logging to /global/scratch/rsoni/spark/bash.222857/log/spark-rsoni-org.apache.spark.deploy.worker.Worker-1-n0086.savio0.out
n0088.savio0: starting org.apache.spark.deploy.worker.Worker, logging to /global/scratch/rsoni/spark/bash.222857/log/spark-rsoni-org.apache.spark.deploy.worker.Worker-1-n0088.savio0.out
n0087.savio0: starting org.apache.spark.deploy.worker.Worker, logging to /global/scratch/rsoni/spark/bash.222857/log/spark-rsoni-org.apache.spark.deploy.worker.Worker-1-n0087.savio0.out


Please use environment variable $SPARK_URL, which is set to spark://n0085.savio0:7077 to connect to spark cluster.
[rsoni@n0085 bash.222857]$ 
[rsoni@n0085 bash.222857]$ 
[rsoni@n0085 bash.222857]$ 
[rsoni@n0085 bash.222857]$ echo $SPARK_DIT

[rsoni@n0085 bash.222857]$ echo $SPARK_DIR 
/global/software/sl-6.x86_64/modules/java/1.8.0_05/spark/1.0.2
[rsoni@n0085 bash.222857]$ spark-submit --master $SPARK_URL $SPARK_DIR/examples/src/main/python/pi.py
Spark assembly has been built with Hive, including Datanucleus jars on classpath
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
15/02/24 12:25:27 INFO SecurityManager: Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
15/02/24 12:25:27 INFO SecurityManager: Changing view acls to: rsoni
15/02/24 12:25:27 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(rsoni)
15/02/24 12:25:28 INFO Slf4jLogger: Slf4jLogger started
15/02/24 12:25:28 INFO Remoting: Starting remoting
15/02/24 12:25:28 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://spark@n0085.savio0:50336]
15/02/24 12:25:28 INFO Remoting: Remoting now listens on addresses: [akka.tcp://spark@n0085.savio0:50336]
15/02/24 12:25:28 INFO SparkEnv: Registering MapOutputTracker
15/02/24 12:25:28 INFO SparkEnv: Registering BlockManagerMaster
15/02/24 12:25:28 INFO DiskBlockManager: Created local directory at /tmp/spark-local-20150224122528-d204
15/02/24 12:25:28 INFO MemoryStore: MemoryStore started with capacity 294.6 MB.
15/02/24 12:25:28 INFO ConnectionManager: Bound socket to port 42969 with id = ConnectionManagerId(n0085.savio0,42969)
15/02/24 12:25:28 INFO BlockManagerMaster: Trying to register BlockManager
15/02/24 12:25:28 INFO BlockManagerInfo: Registering block manager n0085.savio0:42969 with 294.6 MB RAM
15/02/24 12:25:28 INFO BlockManagerMaster: Registered BlockManager
15/02/24 12:25:28 INFO HttpServer: Starting HTTP Server
15/02/24 12:25:29 INFO HttpBroadcast: Broadcast server started at http://10.0.1.85:58690
15/02/24 12:25:29 INFO HttpFileServer: HTTP File server directory is /tmp/spark-75b42c27-4392-4ad4-bf31-b486add50e39
15/02/24 12:25:29 INFO HttpServer: Starting HTTP Server
15/02/24 12:25:29 INFO SparkUI: Started SparkUI at http://n0085.savio0:4040
15/02/24 12:25:30 INFO Utils: Copying /global/software/sl-6.x86_64/modules/java/1.8.0_05/spark/1.0.2/examples/src/main/python/pi.py to /tmp/spark-75ae2060-674a-4520-8b63-0b147f377f7c/pi.py
15/02/24 12:25:30 INFO SparkContext: Added file file:/global/software/sl-6.x86_64/modules/java/1.8.0_05/spark/1.0.2/examples/src/main/python/pi.py at http://10.0.1.85:52635/files/pi.py with timestamp 1424809530524
15/02/24 12:25:30 INFO AppClient$ClientActor: Connecting to master spark://n0085.savio0:7077...
15/02/24 12:25:30 WARN AppClient$ClientActor: Could not connect to akka.tcp://sparkMaster@n0085.savio0:7077: akka.remote.EndpointAssociationException: Association failed with [akka.tcp://sparkMaster@n0085.savio0:7077]
15/02/24 12:25:30 WARN AppClient$ClientActor: Could not connect to akka.tcp://sparkMaster@n0085.savio0:7077: akka.remote.EndpointAssociationException: Association failed with [akka.tcp://sparkMaster@n0085.savio0:7077]
15/02/24 12:25:30 WARN AppClient$ClientActor: Could not connect to akka.tcp://sparkMaster@n0085.savio0:7077: akka.remote.EndpointAssociationException: Association failed with [akka.tcp://sparkMaster@n0085.savio0:7077]
15/02/24 12:25:30 WARN AppClient$ClientActor: Could not connect to akka.tcp://sparkMaster@n0085.savio0:7077: akka.remote.EndpointAssociationException: Association failed with [akka.tcp://sparkMaster@n0085.savio0:7077]
15/02/24 12:25:31 INFO SparkContext: Starting job: reduce at /global/software/sl-6.x86_64/modules/java/1.8.0_05/spark/1.0.2/examples/src/main/python/pi.py:38
15/02/24 12:25:31 INFO DAGScheduler: Got job 0 (reduce at /global/software/sl-6.x86_64/modules/java/1.8.0_05/spark/1.0.2/examples/src/main/python/pi.py:38) with 2 output partitions (allowLocal=false)
15/02/24 12:25:31 INFO DAGScheduler: Final stage: Stage 0(reduce at /global/software/sl-6.x86_64/modules/java/1.8.0_05/spark/1.0.2/examples/src/main/python/pi.py:38)
15/02/24 12:25:31 INFO DAGScheduler: Parents of final stage: List()
15/02/24 12:25:31 INFO DAGScheduler: Missing parents: List()
15/02/24 12:25:31 INFO DAGScheduler: Submitting Stage 0 (PythonRDD[1] at RDD at PythonRDD.scala:37), which has no missing parents
15/02/24 12:25:31 INFO DAGScheduler: Submitting 2 missing tasks from Stage 0 (PythonRDD[1] at RDD at PythonRDD.scala:37)
15/02/24 12:25:31 INFO TaskSchedulerImpl: Adding task set 0.0 with 2 tasks
15/02/24 12:25:46 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient memory
15/02/24 12:25:50 INFO AppClient$ClientActor: Connecting to master spark://n0085.savio0:7077...
15/02/24 12:25:50 WARN AppClient$ClientActor: Could not connect to akka.tcp://sparkMaster@n0085.savio0:7077: akka.remote.EndpointAssociationException: Association failed with [akka.tcp://sparkMaster@n0085.savio0:7077]
15/02/24 12:25:50 WARN AppClient$ClientActor: Could not connect to akka.tcp://sparkMaster@n0085.savio0:7077: akka.remote.EndpointAssociationException: Association failed with [akka.tcp://sparkMaster@n0085.savio0:7077]
15/02/24 12:25:50 WARN AppClient$ClientActor: Could not connect to akka.tcp://sparkMaster@n0085.savio0:7077: akka.remote.EndpointAssociationException: Association failed with [akka.tcp://sparkMaster@n0085.savio0:7077]
15/02/24 12:25:50 WARN AppClient$ClientActor: Could not connect to akka.tcp://sparkMaster@n0085.savio0:7077: akka.remote.EndpointAssociationException: Association failed with [akka.tcp://sparkMaster@n0085.savio0:7077]
15/02/24 12:26:01 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient memory
15/02/24 12:26:10 INFO AppClient$ClientActor: Connecting to master spark://n0085.savio0:7077...
15/02/24 12:26:10 WARN AppClient$ClientActor: Could not connect to akka.tcp://sparkMaster@n0085.savio0:7077: akka.remote.EndpointAssociationException: Association failed with [akka.tcp://sparkMaster@n0085.savio0:7077]
15/02/24 12:26:10 WARN AppClient$ClientActor: Could not connect to akka.tcp://sparkMaster@n0085.savio0:7077: akka.remote.EndpointAssociationException: Association failed with [akka.tcp://sparkMaster@n0085.savio0:7077]
15/02/24 12:26:10 WARN AppClient$ClientActor: Could not connect to akka.tcp://sparkMaster@n0085.savio0:7077: akka.remote.EndpointAssociationException: Association failed with [akka.tcp://sparkMaster@n0085.savio0:7077]
15/02/24 12:26:10 WARN AppClient$ClientActor: Could not connect to akka.tcp://sparkMaster@n0085.savio0:7077: akka.remote.EndpointAssociationException: Association failed with [akka.tcp://sparkMaster@n0085.savio0:7077]
15/02/24 12:26:16 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient memory
15/02/24 12:26:30 ERROR SparkDeploySchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
15/02/24 12:26:30 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool 
15/02/24 12:26:30 INFO TaskSchedulerImpl: Cancelling stage 0
15/02/24 12:26:30 INFO DAGScheduler: Failed to run reduce at /global/software/sl-6.x86_64/modules/java/1.8.0_05/spark/1.0.2/examples/src/main/python/pi.py:38
Traceback (most recent call last):
  File "/global/software/sl-6.x86_64/modules/java/1.8.0_05/spark/1.0.2/examples/src/main/python/pi.py", line 38, in <module>
    count = sc.parallelize(xrange(1, n+1), slices).map(f).reduce(add)
  File "/global/software/sl-6.x86_64/modules/java/1.8.0_05/spark/1.0.2/python/pyspark/rdd.py", line 648, in reduce
    vals = self.mapPartitions(func).collect()
  File "/global/software/sl-6.x86_64/modules/java/1.8.0_05/spark/1.0.2/python/pyspark/rdd.py", line 612, in collect
    bytesInJava = self._jrdd.collect().iterator()
  File "/global/software/sl-6.x86_64/modules/java/1.8.0_05/spark/1.0.2/python/lib/py4j-0.8.1-src.zip/py4j/java_gateway.py", line 537, in __call__
  File "/global/software/sl-6.x86_64/modules/java/1.8.0_05/spark/1.0.2/python/lib/py4j-0.8.1-src.zip/py4j/protocol.py", line 300, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o21.collect.
: org.apache.spark.SparkException: Job aborted due to stage failure: All masters are unresponsive! Giving up.
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1049)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1033)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1031)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1031)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:635)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:635)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:635)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessActor$$anonfun$receive$2.applyOrElse(DAGScheduler.scala:1234)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
	at akka.actor.ActorCell.invoke(ActorCell.scala:456)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by rsoni1** [comment]
Hmm interestingly it's working now... I am able to run both the pi and wordcount examples

**Comment by davclark** [comment]
From Yong Qin:

So after digging through the log this is the culprit.

15/02/24 12:25:30 WARN AppClient$ClientActor: Could not connect to
akka.tcp://sparkMaster@n0085.savio0:7077:
akka.remote.EndpointAssociationException: Association failed with
[akka.tcp://sparkMaster@n0085.savio0:7077]

Apparently master was successfully started but client was not connect
to it. I can't think of any reason that can make this happen unless
there was a network dropped out at that time. I've tried it multiple
times and was not able to reproduce a single case. I've never
encounter similar issues before during my development of the solution
as well.

If similar things happen next time, please ask your user to ssh into
the master node, which should normally be the node that he lands on
from the srun command, and capture outputs from the following commands
so that we can have a better understanding of the issue.

1. ps uxwww
2. lsof|grep 7077

**Comment by davclark** [comment]
From Yong Qin at BRC:

I got some time to verify PySpark and it is working fine to me. Just
follow the instructions that we published on the web and everything
should be good. My sequence of commands as an example.

1. source /global/home/groups/allhands/bin/spark_helper.sh
2. spark-start
3. spark-submit --master $SPARK_URL $SPARK_DIR/examples/src/main/python/pi.py
4. run-example org.apache.spark.examples.SparkPi
5. pyspark $SPARK_DIR/examples/src/main/python/pi.py
6. spark-stop

The first command adds some shell routines to the environment which we
provide to facilitate the environment initialization. The second
command initializes the Spark On Demand (SOD) environment. Command 3
to 5 runs the same PI calculation with different ways. #3 is the
recommended way of launching Spark tasks, while #5 which uses the
PySpark command also works fine albeit obsoleting. The last command
tears down the SOD environment and release resources.

**Comment by rsoni1** [comment]
The Spark processes seem to die after some time. Here is the output of the lsof once I start spark
[rsoni@n0064 bash.228582]$ lsof|grep 7077
lsof: no pwd entry for UID 29
lsof: no pwd entry for UID 29
lsof: no pwd entry for UID 29
lsof: no pwd entry for UID 29
lsof: no pwd entry for UID 29
lsof: no pwd entry for UID 29
lsof: no pwd entry for UID 29
lsof: no pwd entry for UID 29
java      104541    rsoni   28u     IPv6            6058027       0t0                TCP n0064.savio0:7077 (LISTEN)
java      104541    rsoni   47u     IPv6            6058089       0t0                TCP n0064.savio0:7077->n0064.savio0:55488 (ESTABLISHED)
java      104541    rsoni   56u     IPv6            6058096       0t0                TCP n0064.savio0:7077->n0065.savio0:52561 (ESTABLISHED)
java      104541    rsoni   57u     IPv6            6058098       0t0                TCP n0064.savio0:7077->n0066.savio0:47296 (ESTABLISHED)
java      104541    rsoni   58u     IPv6            6058100       0t0                TCP n0064.savio0:7077->n0067.savio0:58804 (ESTABLISHED)
java      104758    rsoni   47u     IPv6            6058088       0t0                TCP n0064.savio0:55488->n0064.savio0:7077 (ESTABLISHED)

And here is the same after a few minutes
[rsoni@n0064 bash.228582]$ lsof|grep 7077
lsof: no pwd entry for UID 29
lsof: no pwd entry for UID 29
lsof: no pwd entry for UID 29
lsof: no pwd entry for UID 29
lsof: no pwd entry for UID 29
lsof: no pwd entry for UID 29
lsof: no pwd entry for UID 29
lsof: no pwd entry for UID 29

These were two consecutive lsof commands within a span of 2 mins after starting spark. WHy would these processes die?

**Comment by davclark** [comment]
I have much to communicate from yesterday, but in particular, I wanted to emphasize that Yong suggested that we always embed our spark jobs in a script that starts with `spark-start` and ends with `spark-stop`. There may be issues that arise from not stopping spark properly on a previous run.

**Comment by rsoni1** [comment]
Ok I have been following Yong's method by using a script (runjob.sh) that starts and stops a cluster around each job.

This works if the job is a small job (counts) but I have now had the same issue appear twice with a longer job (see latest taq.py) where I do a take(5) on saperec

./runjob.sh taq.py 
starting org.apache.spark.deploy.master.Master, logging to /global/scratch/rsoni/spark/bash.229183/log/spark-rsoni-org.apache.spark.deploy.master.Master-1-n0064.savio0.out
n0065.savio0: starting org.apache.spark.deploy.worker.Worker, logging to /global/scratch/rsoni/spark/bash.229183/log/spark-rsoni-org.apache.spark.deploy.worker.Worker-1-n0065.savio0.out
n0064.savio0: starting org.apache.spark.deploy.worker.Worker, logging to /global/scratch/rsoni/spark/bash.229183/log/spark-rsoni-org.apache.spark.deploy.worker.Worker-1-n0064.savio0.out
n0066.savio0: starting org.apache.spark.deploy.worker.Worker, logging to /global/scratch/rsoni/spark/bash.229183/log/spark-rsoni-org.apache.spark.deploy.worker.Worker-1-n0066.savio0.out
n0067.savio0: starting org.apache.spark.deploy.worker.Worker, logging to /global/scratch/rsoni/spark/bash.229183/log/spark-rsoni-org.apache.spark.deploy.worker.Worker-1-n0067.savio0.out


Please use environment variable $SPARK_URL, which is set to spark://n0064.savio0:7077 to connect to spark cluster.
Spark assembly has been built with Hive, including Datanucleus jars on classpath
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
15/03/03 13:57:50 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/03/03 13:57:50 WARN LoadSnappy: Snappy native library not loaded
[[u'080001230', u'D', u'A', u'  TB', 5400, 31.07, u'N', u'00', u'0000000000001375', u'C', u'T', u''], [u'080005357', u'D', u'A', u'  TB', 4300, 31.07, u'N', u'00', u'0000000000001464', u'C', u'T', u''], [u'092052310', u'P', u'A', u'T   ', 100, 31.22, u'N', u'00', u'0000000000007461', u'C', u' ', u''], [u'092817670', u'T', u'A', u'T   ', 200, 31.14, u'N', u'00', u'0000000000008579', u'C', u' ', u''], [u'092817686', u'T', u'A', u' FT ', 100, 31.14, u'N', u'00', u'0000000000008580', u'C', u' ', u'']]
23880473
15/03/03 13:59:34 ERROR TaskSchedulerImpl: Lost executor 1 on n0067.savio0: remote Akka client disassociated
15/03/03 13:59:34 WARN AppClient$ClientActor: Connection to akka.tcp://sparkMaster@n0064.savio0:7077 failed; waiting for master to reconnect...
15/03/03 13:59:34 WARN SparkDeploySchedulerBackend: Disconnected from Spark cluster! Waiting for reconnection...
15/03/03 13:59:34 WARN AppClient$ClientActor: Connection to akka.tcp://sparkMaster@n0064.savio0:7077 failed; waiting for master to reconnect...
15/03/03 13:59:34 ERROR TaskSchedulerImpl: Lost executor 0 on n0064.savio0: remote Akka client disassociated
15/03/03 13:59:34 ERROR TaskSchedulerImpl: Lost an executor 2 (already removed): remote Akka client disassociated
15/03/03 13:59:34 WARN AppClient$ClientActor: Could not connect to akka.tcp://sparkMaster@n0064.savio0:7077: akka.remote.EndpointAssociationException: Association failed with [akka.tcp://sparkMaster@n0064.savio0:7077]
15/03/03 13:59:34 WARN AppClient$ClientActor: Connection to akka.tcp://sparkMaster@n0064.savio0:7077 failed; waiting for master to reconnect...
15/03/03 13:59:34 WARN AppClient$ClientActor: Could not connect to akka.tcp://sparkMaster@n0064.savio0:7077: akka.remote.EndpointAssociationException: Association failed with [akka.tcp://sparkMaster@n0064.savio0:7077]
15/03/03 13:59:34 WARN AppClient$ClientActor: Connection to akka.tcp://sparkMaster@n0064.savio0:7077 failed; waiting for master to reconnect...
15/03/03 13:59:34 WARN AppClient$ClientActor: Could not connect to akka.tcp://sparkMaster@n0064.savio0:7077: akka.remote.EndpointAssociationException: Association failed with [akka.tcp://sparkMaster@n0064.savio0:7077]
15/03/03 13:59:34 WARN AppClient$ClientActor: Connection to akka.tcp://sparkMaster@n0064.savio0:7077 failed; waiting for master to reconnect...
15/03/03 13:59:34 ERROR TaskSchedulerImpl: Lost executor 3 on n0066.savio0: remote Akka client disassociated

**Comment by davclark** [comment]
Yong reports that they have tuned some system parameters, and this should now be fixed. Have a go?

**Comment by rsoni1** [comment]
Ran a long job and the full job processed without any threads crashing...
I'll proceed with the construction of longer jobs.

Out of curiosity what changes were made to affect the stability of these
processes?

Ritesh

**Comment by davclark** [comment]
No idea!

**Comment by davclark** [comment]
I'm hoping this is fixed. I asked about changes, and I'll report back - but my guess is that explaining things is not a priority for the admin team right now.
