### ISSUE TITLE
Compute basic summary stats for a few symbols on one day

### ISSUE THREAD

**Issue by davclark** [berkeley-dsc/dlab-finance#17]
I set up the context for this in the "Example Generators" notebook in pynbbo.

**Comment by rsoni1** [comment]
Dav,

I'm just following this thread and unsure why we wouldn't simply use the spark processing framework setup in nbbo for this rather than the notebook. you need to overwrite the processquote function which currently computes NBBO but can compute almost any summary stat per security. This way you get the speedup from Spark.

**Comment by davclark** [comment]
@rsoni1 this is a learning exercise for @Jay4869. It's not meant to replace a spark-style approach. I'll make a "learning exercise" tag so this kind of thing is clear in the future. And sorry I haven't directed more your way - but I will soon!
